version: '3.0'
networks:
  td-doctrine:
    driver: bridge
services:
  adminer:
    image: adminer
    ports:
      - '8081:8080'
    networks:
      - td-doctrine

  td-doctrine.db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - td-doctrine
    volumes:
      - ./sql:/var/sql

  td-doctrine-php:
    image: 'canals/php:8.2'
    env_file:
      - ./.env
    ports:
      - '8080:80'
    volumes:
      - ./public:/var/www/html
      - ./:/var/www
    networks:
      td-doctrine:
        aliases:
          - td-doctrine.local
    depends_on:
      - td-doctrine.db
