version: '3.0'

services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'mdp'
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    ports:
      - '8080:8080'

  php:
    image: 'php:latest'
    ports:
      - '2780:80'
      - '2743:443'
    volumes:
      - ./src:/var/www/html
    depends_on:
      -  db
